### PR TITLE
add def to 'bonding behavior'. closes #75

### LINKED ISSUE #75: need definition for bonding behavior
NBO_0000043  bonding behavior
**proposed def:** A behavior that occurs between two individuals, such as parent and child, and involves an emotional attachment that implies a special and focused relationship.
**source:** PMID:29327315

### PR DESCRIPTION
**Pull request by nicolevasilevsky**

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
@matentzn I didn't know the preferred format for annotations - I used definition and annotated the PMID as a dbxref on the def itself (as we do in HPO, Mondo, etc.)

**Comment by matentzn** [comment]
I fixed the diff. Can you review it again?

The problem was that somehow your protege turned:

```
<rdf:RDF xmlns="http://purl.obolibrary.org/obo/nbo.owl#"
     xml:base="http://purl.obolibrary.org/obo/nbo.owl"
```

into:

```
<rdf:RDF xmlns="http://purl.obolibrary.org/obo/nbo.owl/"
     xml:base="http://purl.obolibrary.org/obo/nbo.owl/"
```

Watch out for these kind of issues, that changed the whole ontology! :D

**Comment by nicolevasilevsky** [comment]
Wow - it just removed a # ? Crazy

**Comment by nicolevasilevsky** [comment]
I think this looks okay, thanks! Do you want to merge it @matentzn?

**Comment by nicolevasilevsky** [comment]
(Although I still have the question - did I add the def and dbxref correctly?)

**Comment by matentzn** [comment]
Looks fine in protege. A bit redundant in owlxml..

**Pull request merged**
