### PR TITLE
Obsolete behavioral control of excretion

### LINKED ISSUE #115: obsolete: behavioral control of excretion
GO is obsoleting excretion:

https://github.com/geneontology/go-ontology/issues/22368

NBO has a term "behavioral control of excretion". GO believes excretion is not a useful grouping, so this NBO concept should be replaced by more specific terms:

http://purl.obolibrary.org/obo/NBO_0000038

### PR DESCRIPTION
**Pull request by DitchingIt**
Fixes #115

### CODE REVIEW

**Comment by matentzn** [comment]
Sorry @DitchingIt - I am not the right person for reviewing content changes to any ontology (I have a rule: don't look at content - else I will never be able to do any work); I would recommend @sbello or @rays22 as

**Review by rays22 — CHANGES_REQUESTED** [review]
Please, do not obsolete [NBO:0000038 behavioral control of excretion](https://www.ebi.ac.uk/ols/ontologies/NBO/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNBO_0000038).
Instead, remove the axiom
* Equivalent to:
[emission behavior](https://www.ebi.ac.uk/ols/ontologies/nbo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNBO_0000035) and [is_about](https://www.ebi.ac.uk/ols/ontologies/nbo/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2Fnbo%23is_about) some [excretion](https://www.ebi.ac.uk/ols/ontologies/nbo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0007588)

Fo further explanation, please find my comments [here](https://github.com/obo-behavior/behavior-ontology/issues/115#issuecomment-1449988085).

**Comment by DitchingIt** [comment]
Hi @rays22 
Not sure if you've seen my resubmitted PR or have I made a mistake in the process?
Thanks

**Review by matentzn — APPROVED** [review]
This is ready to merge!

**Pull request merged**
